# Generated by Django 5.0.2 on 2024-03-07 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsline', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='type',
            field=models.CharField(choices=[('ME', 'Мемы'), ('FO', 'Поиск команды')], max_length=13, null=True),
        ),
    ]
