# Generated by Django 5.0.2 on 2024-03-13 02:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newsline', '0004_profile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
