# Generated by Django 5.0.2 on 2024-03-13 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsline', '0007_delete_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='accept',
            field=models.BooleanField(default=True, null=True),
        ),
    ]
