# Generated by Django 5.0.2 on 2024-03-14 02:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsline', '0008_message_accept'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='accept',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
