# Generated by Django 5.0.2 on 2024-03-10 09:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sign', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='authcode',
            name='user',
        ),
    ]
