# Generated by Django 5.0.2 on 2024-03-10 10:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sign', '0003_authcode_username'),
    ]

    operations = [
        migrations.RenameField(
            model_name='authcode',
            old_name='username',
            new_name='user',
        ),
    ]
