# Generated by Django 5.0.2 on 2024-03-13 01:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sign', '0005_remove_authcode_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AuthCode',
        ),
    ]
